### ISSUE TITLE
error when tracking other objects by using sort 

### ISSUE THREAD

**Issue by DeanHao** [bendidi/Tracking-with-darkflow#20]
HI,bendidi!  I met some problem when trying to track cars.
9.893 FPSTraceback (most recent call last):
  File "run.py", line 26, in <module>
    tfnet.camera()
  File "F:\Tracking-with-darkflow\darkflow\darkflow\net\help.py", line 171, in camera
    encoder=encoder,tracker=tracker)
  File "F:\Tracking-with-darkflow\darkflow\darkflow\net\yolov2\predict.py", line 124, in postprocess
    trackers = tracker.update(detections)
  File "F:\Tracking-with-darkflow\sort\sort.py", line 213, in update
    trk.update(dets[d,:][0])
IndexError: too many indices for array
I use python3.5,am i use the wrong version of python?
thank you!

**Comment by bendidi** [comment]
should be fixed with latest commit !

**Comment by DeanHao** [comment]
I found out what the problem is. It comes out when the first frame doesn't show the tracked object.
