### ISSUE TITLE
Performance in terms of objects

### ISSUE THREAD

**Issue by ashnarayan13** [bendidi/Tracking-with-darkflow#23]
I wanted to know how many objects can be tracked in each frame as the README doesn't clearly state it. 

Also, I wanted to know if this can be extended to track objects of different classes. Like, people, animals simultaneously. (Yolo can do that, but can the tracking keep the IDs?) 

Thanks

**Comment by bendidi** [comment]
I don't think there is a limit to the number of objects tracked in each frame, and the current implementation can track objects of different classes (by giving a list of class names to the trackObj FLAG) but it will not keep the name of the classes while tracking , it will just show the tracking number ID

**Comment by ashnarayan13** [comment]
Thanks! 
Also, what weights do I use, using YOLO weights is giving a tensor flow error. 
The yolo weights from the official darknet website if yolo weights for the C and CUDA implementation, where can I get the Tensorflow weights and cfg? 

# FLAGS.model = "darkflow/cfg/yolo.cfg" # tensorflow model
# FLAGS.load = "darkflow/bin/yolo.weights" # tensorflow weights
FLAGS.pbLoad = "tiny-yolo-voc-traffic.pb" # tensorflow model
FLAGS.metaLoad = "tiny-yolo-voc-traffic.meta" # tensorflow weights

Thanks again!

**Comment by bendidi** [comment]
you can get YOLO weights from [here](https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU)

**Comment by ashnarayan13** [comment]
Thanks. The weights don't seem to be a problem. Tensorflow is not built for CUDA 9 yet and hence the run.py is not working. 
Even after setting GPU to 0. I get a tensorflow error

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from darkflow.darkflow.net.build import TFNet
  File "/home/ashwath/fortiss/Tracking-with-darkflow/darkflow/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ashwath/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

**Comment by bendidi** [comment]
the error is because you are using tensorflow-gpu , and yes tensorflow does not support cuda-9 yet , you can install cuda-8 simply using `apt-get install cuda-8.0`

**Comment by ashnarayan13** [comment]
Got it working on CPU instead. Thank you so much for the quick response!
