### ISSUE TITLE
No tracking code has been included

### ISSUE THREAD

**Issue by Zumbalamambo** [bendidi/Tracking-with-darkflow#27]
I tried setting the param to camera and have enabled tracking but in no way its tracking...

**Comment by bendidi** [comment]
test it without tracking enabled , and check if there are detections , if there is no detection then it's normal that there will be no tracking

**Comment by ibrahim-ai** [comment]
hi @bendidi , while i disable tracking than it's correctly detected all the persons but when i enable the tracking (with deep_short) than there is no detection or tracking at all. also while i try to run only short with tracking enable, there's a lot's of false detection/tracking.. 

another thing when i use "FLAGS.saveVideo = True" than i got this error
Traceback (most recent call last):
  File "/home/Tracking-with-darkflow/run.py", line 30, in <module>
    tfnet.camera()
  File "/home/Tracking-with-darkflow/darkflow/darkflow/net/help.py", line 124, in camera
    fps = 1 / self._get_fps(frame)
  File "/home/Tracking-with-darkflow/darkflow/darkflow/net/help.py", line 66, in _get_fps
    processed = self.framework.postprocess(net_out, frame)
  File "/home/Tracking-with-darkflow/darkflow/darkflow/net/yolov2/predict.py", line 107, in postprocess
    detections = detections + extract_boxes(self,mask)
  File "/home/Tracking-with-darkflow/darkflow/darkflow/net/yolov2/predict.py", line 40, in extract_boxes
    new_im=new_im.astype(np.uint8)
AttributeError: 'NoneType' object has no attribute 'astype
