### ISSUE TITLE
AttributeError: 'module' object has no attribute 'bgsegm'

### ISSUE THREAD

**Issue by nidhinkk** [bendidi/Tracking-with-darkflow#42]
This error was generated when I run the file

Running entirely on CPU
2018-02-20 11:13:14.834956: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Finished in 5.81529521942s
Traceback (most recent call last):
  File "run.py", line 30, in <module>
    tfnet.camera()
  File "/home/itsme/Documents/Tracking-with-darkflow-master/Tracking-with-darkflow/darkflow/darkflow/net/help.py", line 88, in camera
    fgbg = cv2.bgsegm.createBackgroundSubtractorMOG()
AttributeError: 'module' object has no attribute 'bgsegm'

Can anybody tell whats the issue?

**Comment by seovchinnikov** [comment]
whats your version of opencv? bgsegm is in contrib module of opencv but it was unified with the main module some time ago

**Comment by nidhinkk** [comment]
Opencv version is 3.4.0

**Comment by seovchinnikov** [comment]
if you  have not built contrib module,
pip install opencv-contrib-python

**Comment by nidhinkk** [comment]
It works. Thanks for the help.
