### ISSUE TITLE
How to solve Windows 10 error: Cannot open include file: 'numpy/arrayobject.h': No such file or directory

### ISSUE THREAD

**Issue by Jumabek** [bendidi/Tracking-with-darkflow#5]
Hi @bendidi , 
I am trying to run the demo, however `python run.py` giving me following errors:

`
cy_yolo_findboxes.c
C:\Users\jumab\.pyxbld\temp.win-amd64-3.5\Release\pyrex\darkflow\darkflow\cython_utils\cy_yolo_findboxes.c(475): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow\lib\distutils\_msvccompiler.py", line 382, in compile
    self.spawn(args)
  File "C:\Anaconda3\envs\tensorflow\lib\distutils\_msvccompiler.py", line 501, in spawn
    return super().spawn(cmd)
  File "C:\Anaconda3\envs\tensorflow\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Anaconda3\envs\tensorflow\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Anaconda3\envs\tensorflow\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

I know another issue had the same problem, but my OS is windows 10 this time.

**Comment by bendidi** [comment]
try building darkflow in place ,in darkflow run the following command : 

`python3 setup.py build_ext --inplace`

**Comment by Jumabek** [comment]
Yep, that solved the problem !

**Comment by Hamza1996780** [comment]
Hi i am getting the same error plz help to resolve.
